### ISSUE TITLE
Annotation Vector file missing from latest matrixprofile-ts build

### ISSUE THREAD

**Issue by nikita-smyrnov** [target/matrixprofile-ts#92] opened 2020-02-07 19:17 UTC
Apparently the annotation_vector.py file isn't present when using pip to install matrixprofile-ts. Is the version on PyPi outdated? Would like to use the annotation vector feature if possible.

**Comment by vanbenschoten** [comment] 2020-02-07 20:07
@nikita-smyrnov it looks like the issue is that annotation_vector isn't included in the _init_.py file. You can either build the library straight from the GitHub repo, or make a PR to fix the above _init_.py issue. If you can do that then I'll push to pip.

**Comment by nikita-smyrnov** [comment] 2020-02-10 15:57
Fixed the init.py. Tested and should be working properly now.

**Comment by frankiecancino** [comment] 2020-02-11 21:38
Merged the PR. Closing the issue.

**Closed by frankiecancino** 2020-02-11 21:38 UTC
